### ISSUE TITLE
iptables v1.4.21: Set unblock doesn't exist.

### ISSUE THREAD

**Issue by DoplerGanger** [Sharm/keenetic-domain-routing#1]
Проблема на этапе ручного запуска скрипта.
при запуске соответственно добавляет все рулы кроме 
iptables -t mangle -A PREROUTING -p all -m mark --mark 0xffffaac -m set --match-set unblock dst -j DOMAIN_VPN

если назначить политику устройству VPN (у меня она называется Full_VPN) То устройство спокойно выходит через тунель wireguard и позволяет сёрфить инет без вопросов.

после назначения политики Domain_VPN (у меня она называется так же) устройство выходит через стандартного провайдера.
резолв через кинетик пашет - адреса отдаёт.
конфигурация dnsmasq:
`/opt/etc # cat unblock.dnsmasq
#ipset
ipset=/intel.com/unblock

#global static upstream dns server
server=1.1.1.1`

как видно тещу на домене intel.com (который без впн открывается но с предупреждением мол вы в бане).
через впн должен открываться нормально.

kn-1011
4.1.7
Подскажи что не так ?

**Comment by Sharm** [comment]
Надо диагностировать.
Например, убедиться, что dns запросы проходят через роутер и dnsmasq, для этого можно
перезапустить dnsmasq, очистить таблицу unblock `ipset flush unblock`, зайти клиентом на intel.com и проверь таблицу unblock: `ipset list unblock`. В ней должны появиться ip адреса. ip адреса должны совпадать с теми, что получит клиент при запросе `nslookup intel.com`. Предполагаем, что клиент на Windows.

Про 
> при запуске соответственно добавляет все рулы кроме
> iptables -t mangle -A PREROUTING -p all -m mark --mark 0xffffaac -m set --match-set unblock dst -j DOMAIN_VPN

Не понял, нужно больше контекста. Как запускаешь, как устанавливаешь правила, где и как установлен shadowsocks. Но вероятно из-за этого и не работает.

**Comment by DoplerGanger** [comment]
https://github.com/Sharm/keenetic-domain-routing/blob/master/VPN.md
я конкретно про этот гайд.
По поводу первого абзаца сейчас проверим

**Comment by DoplerGanger** [comment]
ipset v7.21: The set with the given name does not exist
Похоже таблица unblock Вообще не появляется.

**Comment by Sharm** [comment]
Действительно, видимо пропущено в этой инструкции.

Добавь в скрипт
```
ipset list unblock > /dev/null 2>&1 && ipset flush unblock # flush if set exists
ipset create unblock hash:net -exist
```
По аналогии с [TCP](https://github.com/Sharm/keenetic-domain-routing/blob/master/SHADOWSOCKS_TCP.md#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%B0%D1%86%D0%B8%D0%B8-iptables)

Первую строчку, где сброс содержимого таблицы - по желанию. Она может давать иногда больше проблем чем пользы, например если таблица очистится, а DNS кэш - нет.

**Comment by DoplerGanger** [comment]
Да так и есть. Всё заработало, осталось внести в "автозапуск" по тригеру.
Но есть вопросик, каждый раз когда я буду добавлять домен в файлик dnsmasq требуется ли перезапуск службы dnsmasq?

**Comment by Sharm** [comment]
Да, нужно перезапускать dnsmasq
